[package]
name = "pz-rm-extractor"
version = "1.0.0"
edition = "2021"
publish = false

[profile.release]
lto = "thin"
codegen-units = 1
strip = true

[dependencies]
regex = "1"
rlua = "0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"