name: build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-unknown-linux-gnu

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-gnu --release --manifest-path pz-rm-extractor/Cargo.toml

    - name: Upload built RM extractor
      uses: actions/upload-artifact@v3
      with:
        name: pz-rm-extractor
        path: pz-rm-extractor/target/x86_64-unknown-linux-gnu/release/pz-rm-extractor