name: ci

on:
  push:
    paths:
      - 'pz-rm-extractor/**/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-unknown-linux-gnu

    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --target x86_64-unknown-linux-gnu --release --manifest-path pz-rm-extractor/Cargo.toml