name: generate

on:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types:
      - completed
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - '!*'
    paths:
      - '.github/workflows/generate.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Download pz-rm-extractor artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        name: pz-rm-extractor
        path: /tmp/pz-rm-extractor

    - name: SteamCMD
      run: mkdir ~/SteamCMD && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxf - -C ~/SteamCMD

    - name: Install Project Zomboid Dedicated Server
      run: ~/SteamCMD/steamcmd.sh +force_install_dir ~/pz-rm-explorer +login anonymous +app_update 380870 validate +quit

    - name: Generate
      run: /tmp/pz-rm-extractor/pz-rm-extractor docs/extracted.json

    - name: Commit
      run: |
        git config --local user.email "$(git log --format='%ae' HEAD^!)"
        git config --local user.name "$(git log --format='%an' HEAD^!)"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add -f docs/extracted.json
        git commit -m "Update extracted recorded media JSON"
        git push github HEAD:${GITHUB_REF}