name: generate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - '*.*.*'
    paths:
      - '.github/workflows/generate.yml'

jobs:
  generate:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-unknown-linux-gnu

    - uses: Swatinem/rust-cache@v1

    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-gnu --release --manifest-path pz-rm-extractor/Cargo.toml

    - name: Cache Project Zomboid Dedicated Server
      uses: actions/cache@v2
      with:
        key: pz-dedicated-server
        path: |
          /tmp/pz-rm-explorer
          /tmp/SteamCMD

    - name: SteamCMD
      run: mkdir /tmp/SteamCMD && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxf - -C /tmp/SteamCMD

    - name: Install Project Zomboid Dedicated Server
      run: /tmp/SteamCMD/steamcmd.sh +force_install_dir /tmp/pz-rm-explorer +login anonymous +app_update 380870 validate +quit

    - name: Generate
      run: chmod +x /tmp/pz-rm-extractor/pz-rm-extractor && /tmp/pz-rm-extractor/pz-rm-extractor docs/extracted.json

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/extracted.json
        git commit -m "Update extracted recorded media JSON"
        git push