name: generate

on:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types:
      - completed
  schedule:
    - cron: '0 0 * * *'
  push:
    tags:
      - '!*'
    paths:
      - '.github/workflows/generate.yml'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download pz-rm-extractor artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
        workflow_conclusion: success
        name: pz-rm-extractor
        path: /tmp/pz-rm-extractor

    - name: Cache Project Zomboid Dedicated Server
      uses: actions/cache@v2
      with:
        key: pz-dedicated-server
        path: /tmp/pz-rm-explorer

    - name: SteamCMD
      run: mkdir /tmp/SteamCMD && curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxf - -C /tmp/SteamCMD

    - name: Install Project Zomboid Dedicated Server
      run: /tmp/SteamCMD/steamcmd.sh +force_install_dir /tmp/pz-rm-explorer +login anonymous +app_update 380870 validate +quit

    - name: Generate
      run: chmod +x /tmp/pz-rm-extractor/pz-rm-extractor && /tmp/pz-rm-extractor/pz-rm-extractor docs/extracted.json

    - name: Commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -f docs/extracted.json
        git commit -m "Update extracted recorded media JSON"
        git push